version: '3'

services:
  app:
    build: .
    command: node index.js
    environment:
      - MAILHOG_HOST=mailhog

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025